apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: dapr-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dapr-sentry-root-ca
spec:
  secretName: dapr-sentry-root-ca
  commonName: dapr-sentry-root-ca-from-cert-manager
  duration: 43800h  # 5 years (24h * 365 * 5)
  renewBefore: 2160h  # 90 days (24h * 90)
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: selfsigned
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: dapr-trust-bundle
  namespace: dapr-system
spec:
  ca:
    secretName: dapr-sentry-root-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dapr-trust-bundle
  namespace: dapr-system
spec:
  secretName: dapr-trust-bundle-from-cert-manager
  commonName: dapr-sentry-issuer-from-cert-manager
  duration: 8760h  # 1 year (24h * 365)
  renewBefore: 2160h  # 90 days (24h * 90)
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  dnsNames:
  - cluster.local
  issuerRef:
    name: dapr-trust-bundle