{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dapr-trustbundle.fullname" . }}-operator-metrics-service
  namespace: {{ include "dapr-trustbundle.namespace" . }}
  labels:
    {{- include "dapr-trustbundle.controllerLabels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: {{ .Values.metrics.port }}
  selector:
    {{- include "dapr-trustbundle.controllerSelectorLabels" . | nindent 4 }}
{{- end }}
