{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dapr-trustbundle.fullname" . }}-controller-manager
  namespace: {{ .Values.metrics.serviceMonitor.namespace | default (include "dapr-trustbundle.namespace" .) }}
  labels:
    {{- include "dapr-trustbundle.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - interval: {{ .Values.metrics.serviceMonitor.interval }}
    path: /metrics
    port: https
    scheme: https
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      {{- include "dapr-trustbundle.controllerSelectorLabels" . | nindent 6 }}
{{- end }}
